## ACM-W, MTC and MSPs present: Data Science Series - Session 1: The Numpy Stack

## Section 1: Numpy 

In [0]:
import numpy as np

In [61]:
#Creating a numpy array from python array
l = [1,2,3,4]
l_np = np.array(l)
print("1 dimensional vector: ",l_np)
print("Shape of vector: ",l_np.shape)
print("Number of dimensions: ",l_np.ndim)
print("Size of vector",l_np.size,"\n")
l_2 = [[1,2],[3,4]]
l_2_np = np.array(l_2)
print("2 dimensional matrix: ",l_2_np)
print("Shape of array: ",l_2_np.shape)
print("Number of dimensions: ",l_2_np.ndim)
print("Size of matrix",l_2_np.size,"\n")
#Creating numpy array of random number
l_3_np = np.random.rand(3,3)
print("Creating a random matrix of values between 0 and 1:\n",l_3_np,"\n")

l_4_np = np.random.randint(10,size=(3,3))
print("Creating a random matrix of integer values between 0 and 10",l_4_np,"\n")

l_5_np = np.random.randn(3,3)
print("Creating a random matrix of values between 0 and 1 with mean around 0 and variance around 1",l_5_np,"\n")
print("MEAN:",l_5_np.mean())
print("VARIANCE:",l_5_np.var())

1 dimensional vector:  [1 2 3 4]
Shape of vector:  (4,)
Number of dimensions:  1
Size of vector 4 

2 dimensional matrix:  [[1 2]
 [3 4]]
Shape of array:  (2, 2)
Number of dimensions:  2
Size of matrix 4 

Creating a random matrix of values between 0 and 1:
 [[0.74733717 0.48579778 0.11359617]
 [0.38737047 0.71312626 0.1330726 ]
 [0.57429332 0.44797086 0.87380091]] 

Creating a random matrix of integer values between 0 and 10 [[8 3 6]
 [4 7 3]
 [3 7 7]] 

Creating a random matrix of values between 0 and 1 with mean around 0 and variance around 1 [[ 0.0932354   1.91791659 -0.24173691]
 [ 0.09388054  0.34763063 -0.29099517]
 [-0.0689341   0.76861469  0.61977802]] 

MEAN: 0.35993218818758194
VARIANCE: 0.4192841152452231


In [62]:
#Vector: D=1
#Matrix: D>2
v = [1,0.5,4]
v_np = np.array(v)
print(v_np+2)
print(v_np/2)
print(v_np*2)
print(v_np-2)

[3.  2.5 6. ]
[0.5  0.25 2.  ]
[2. 1. 8.]
[-1.  -1.5  2. ]


In [63]:
#Two numpy operations
a = np.array([1,2,3])
b = np.array([4,5,6])
#Arithmetic
print("Arithmetic Operations:")
print(a+b)
print(a-b)
print(a*b)
print(a/b)
#Stacking two vectors
print("\nStacking two vectors.")
print("Horizontal: ",np.hstack((a,b)))
print("Vertical: ",np.vstack((a,b)))
#Creating plain matrices of zeroes and ones
print("\nCreating zero matrix of (3,3), one matrix of (3,3) and identity matrix of (3,3).")
zero = np.zeros((3,3))
print("Zero Matrix\n",zero)
one = np.ones((3,3))
print("One Matrix\n",one)
id = np.eye(3) #Identity Matrix
print("Identity Matrix\n",id)

Arithmetic Operations:
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]

Stacking two vectors.
Horizontal:  [1 2 3 4 5 6]
Vertical:  [[1 2 3]
 [4 5 6]]

Creating zero matrix of (3,3), one matrix of (3,3) and identity matrix of (3,3).
Zero Matrix
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
One Matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [76]:
#Slicing/Indexing Numpy Arrays
s = np.random.randint(10,size=(3,3))
print("Random Matrix:\n",s,"\n")

Random Matrix:
 [[4 7 3]
 [8 4 8]
 [0 8 7]] 



In [85]:
print("Printing out the first row: ",s[0,:])
print("Printing out the first row: ",s[:,0])
print("Printing a 2x2 out of the 3x3 matrix: ",s[np.ix_([0,1],[0,1])])
print("Printing a 2x2 out of the 3x3 matrix: ",s[0:2,0:2])

Printing out the first row:  [4 7 3]
Printing out the first row:  [4 8 0]
Printing a 2x2 out of the 3x3 matrix:  [[4 7]
 [8 4]]
Printing a 2x2 out of the 3x3 matrix:  [[4 7]
 [8 4]]


## Section 2: Pandas

## Section 3: Matplotlib
